name: PR Preview Zip

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-preview-zip:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Create PR Preview Zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'hass-custom-csnet-home.zip'
          directory: ./custom_components/csnet_home

      - name: Upload PR Preview Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: csnet_home-pr-preview
          path: ./custom_components/csnet_home/hass-custom-csnet-home.zip
          if-no-files-found: error

      - name: Add PR comment with artifact hint
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v8
        with:
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const body = [
              'A preview ZIP has been generated for this PR.\n',
              `- Artifact name: csnet_home-pr-preview\n`,
              `- Download from the workflow run: ${runUrl}`,
            ].join('');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });

