---
name: PR Preview Zip

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'custom_components/csnet_home/**'
      - '.github/workflows/pr-preview.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  build-preview-zip:
    name: Build Preview Artifact
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Get PR Info
        id: pr_info
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          {
            echo "pr_number=${{ github.event.pull_request.number }}"
            echo "pr_title=${PR_TITLE}"
            echo "pr_sha=${GITHUB_SHA:0:7}"
          } >> "$GITHUB_OUTPUT"

      - name: Create PR Preview Zip
        run: |
          cd custom_components/csnet_home
          rm -f hass-custom-csnet-home.zip
          zip -r hass-custom-csnet-home.zip . \
            -x "*.git*" \
            -x "*__pycache__*" \
            -x "*.pyc" \
            -x "*.pyo" \
            -x "*.DS_Store" \
            -x "*.pytest_cache*"
          ls -lh hass-custom-csnet-home.zip
          echo "✅ Preview zip created successfully"

      - name: Upload PR Preview Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: csnet_home-pr-preview
          path: ./custom_components/csnet_home/hass-custom-csnet-home.zip
          if-no-files-found: error
          retention-days: 30

      - name: Find existing comment
        id: find_comment
        uses: peter-evans/find-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: 'PR Preview Artifact'

      - name: Add or Update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## 📦 PR Preview Artifact

            A preview ZIP has been generated for this PR.

            **Details:**
            - 🔖 Artifact name: `csnet_home-pr-preview`
            - 📝 Commit: `${{ steps.pr_info.outputs.pr_sha }}`
            - ⏱️ Retention: 30 days

            **Download:**
            - [Download from workflow run](${{ github.server_url }}/${{
              github.repository }}/actions/runs/${{ github.run_id }})

            **Installation:**
            1. Stop Home Assistant
            2. Extract the ZIP to `config/custom_components/csnet_home`
            3. Restart Home Assistant
            4. Test the changes

            ⚠️ **Note:** This is a preview build. Use for testing purposes only.
